using System;
using System.Collections;
using System.Collections.Generic;

namespace Galvarino.Web.Models.Helper
{
    public sealed class ProcesoDocumentos
    {
        public static readonly string NOMBRE_PROCESO = "SOLICITUD_CUSTODIA_DOCUMENTOS";
        public static readonly string ETAPA_ENVIO_NOTARIA = "ENVIO_NOTARIA";
        public static readonly string ETAPA_DESPACHO_OFICINA_NOTARIA = "DESPACHO_OFICINA_NOTARIA";
        public static readonly string ETAPA_RECEPCION_SET_LEGAL = "RECEPCION_SET_LEGAL";
        public static readonly string ETAPA_RECEPCION_NOTARIA = "RECEPCION_NOTARIA";
        public static readonly string ETAPA_REVISION_DOCUMENTOS = "REVISION_DOCUMENTOS";
        public static readonly string ETAPA_DESPACHO_REPARO_NOTARIA = "DESPACHO_REPARO_NOTARIA";
        public static readonly string ETAPA_DESPACHO_OFICINA_PARTES = "DESPACHO_OFICINA_PARTES";
        public static readonly string ETAPA_RECEPCION_VALIJA_OFICINA_PARTES = "RECEPCION_VALIJA_OFICINA_PARTES";
        public static readonly string ETAPA_RECEPCION_VALIJA_MESA_CONTROL = "RECEPCION_VALIJA_MESA_CONTROL";
        public static readonly string ETAPA_ANALISIS_MESA_CONTROL = "ANALISIS_MESA_CONTROL";
        public static readonly string ETAPA_DESPACHO_OF_PARTES_DEVOLUCION = "DESPACHO_OF_PARTES_DEVOLUCION";
        public static readonly string ETAPA_DESPACHO_OFICINA_CORRECCION = "DESPACHO_OFICINA_CORRECCION";
        public static readonly string ETAPA_SOLUCION_REPAROS_SUCURSAL = "SOLUCION_REPAROS_SUCURSAL";
        public static readonly string ETAPA_DESPACHO_A_CUSTODIA = "DESPACHO_A_CUSTODIA";
        public static readonly string ETAPA_RECEPCION_Y_CUSTODIA = "RECEPCION_Y_CUSTODIA";
        public static readonly string ETAPA_APERTURA_VALIJA = "APERTURA_VALIJA";
        public static readonly string ETAPA_DOCUMENTACION_FALTANTE = "DOCUMENTACION_FALTANTE";
        public static readonly string ETAPA_PREPARAR_NOMINA = "PREPARAR_NOMINA";
        public static readonly string ETAPA_ENVIO_A_NOTARIA_RM = "ENVIO_A_NOTARIA_RM";
        public static readonly string ETAPA_RECEPCION_DE_NOTARIA_RM = "RECEPCION_DE_NOTARIA_RM";
        public static readonly string ETAPA_REVISION_DOCUMENTOS_NOTARIA_RM = "REVISION_DOCUMENTOS_NOTARIA_RM";
        public static readonly string ETAPA_DEVOLUCION_REPARO_NOTARIA_RM = "DEVOLUCION_REPARO_NOTARIA_RM";
        public static readonly string ETAPA_ANALISIS_MESA_CONTROL_NOMINA_ESPECIAL = "ANÁLISIS_NÓMINA_ESPECIAL";
        public static readonly string ETAPA_DESPACHO_A_CUSTODIA_NÓMINA_ESPECIAL = "DESPACHO_A_CUSTODIA_NÓMINA_ESPECIAL";
        public static readonly string ETAPA_NOMINA_SET_COMPLEMENTARIO = "SOLICITUD_SET_COMPLEMENTARIO";
        public static readonly string ETAPA_PREPARAR_NOMINA_SET_COMPLEMENTARIO = "PREPARAR_NÓMINA_SET_COMPLEMENTARIO";
        public static readonly string ETAPA_DESPACHO_OFICINA_DE_PARTES_SET_COMPLEMENTARIO = "DESPACHO_OFICINA_DE_PARTES_SET_COMPLEMENTARIO";
        public static readonly string ETAPA_RECEPCIÓN_OFICINA_DE_PARTES_SET_COMPLEMENTARIO = "RECEPCIÓN_OFICINA_DE_PARTES_SET_COMPLEMENTARIO";
        public static readonly string ETAPA_RECEPCIÓN_VALIJA_MESA_CONTROL_SET_COMPLEMENTARIO = "RECEPCIÓN_VALIJA_MESA_CONTROL_SET_COMPLEMENTARIO";
        public static readonly string ETAPA_APERTURA_VALIJA_SET_COMPLEMENTARIO = "APERTURA_VALIJA_SET_COMPLEMENTARIO";
        public static readonly string ETAPA_ANALISIS_MESA_CONTROL_SET_COMPLEMETARIOS= "ANALISIS_MESA_CONTROL_SET_COMPLEMETARIOS";
        public static readonly string ETAPA_DESPACHO_A_CUSTODIA_SET_COMPLEMENTARIO= "DESPACHO_A_CUSTODIA_SET_COMPLEMENTARIO";
        public static readonly string ETAPA_DESPACHO_DOCUMENTO_OFICINA_DESTINO = "DESPACHO_DOCUMENTO_OFICINA_DESTINO";
        public static readonly string ETAPA_RECEPCION_Y_CUSTODIA_SET_COMPLEMENTARIO = "RECEPCION_Y_CUSTODIA_SET_COMPLEMENTARIO";
        public static readonly string ETAPA_DESPACHO_A_DOCUMENTOS_A_SUCURSAL = "DESPACHO_A_DOCUMENTOS_A_SUCURSAL";
        public static readonly string ETAPA_RECEPCION_VALIJA_DOCUMENTOS_OFICINA_DESTINO = "RECEPCION_VALIJA_DOCUMENTOS_OFICINA_DESTINO";
        public static readonly string ETAPA_APERTURA_VALIJA_DOCUMENTOS_OFICINA_DESTINO = "APERTURA_VALIJA_DOCUMENTOS_OFICINA_DESTINO";
        public static readonly string ETAPA_ENTREGA_DE_DOCUMENTOS_CREDITO = "ENTREGA_DE_DOCUMENTOS_CREDITO";
        public static readonly string ETAPA_SOLUCION_REPAROS_SUCURSAL_PAGADORA = "SOLUCION_REPAROS_SUCURSAL_PAGADORA";


    }
}