// <auto-generated />
using System;
using Galvarino.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Galvarino.Web.data.migrations.pensionado
{
    [DbContext(typeof(PensionadoDbContext))]
    [Migration("20230417214023_CargasInicialesAgregarKey")]
    partial class CargasInicialesAgregarKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pensionado")
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Galvarino.Web.Models.Application.Pensionado.CargasIniciales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DvPensionado");

                    b.Property<string>("Estado");

                    b.Property<DateTime>("FechaCarga");

                    b.Property<DateTime>("FechaEfectiva");

                    b.Property<DateTime>("FechaProceso");

                    b.Property<DateTime>("FechaSolicitud");

                    b.Property<string>("Folio");

                    b.Property<string>("Forma");

                    b.Property<string>("NombrePensionado");

                    b.Property<string>("RutPensionado");

                    b.Property<int?>("SucursalId");

                    b.Property<int?>("TipoId");

                    b.Property<string>("TipoMovimiento");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.HasIndex("TipoId");

                    b.ToTable("CargasIniciales");
                });

            modelBuilder.Entity("Galvarino.Web.Models.Application.Pensionado.HomologacionOficinas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdOficina");

                    b.Property<string>("IdSucursalActividad")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("HomologacionOficinas");
                });

            modelBuilder.Entity("Galvarino.Web.Models.Application.Pensionado.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SucursalDescripcion")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Sucursal");
                });

            modelBuilder.Entity("Galvarino.Web.Models.Application.Pensionado.Tipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TipoDescripcion")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Tipo");
                });

            modelBuilder.Entity("Galvarino.Web.Models.Application.Pensionado.CargasIniciales", b =>
                {
                    b.HasOne("Galvarino.Web.Models.Application.Pensionado.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId");

                    b.HasOne("Galvarino.Web.Models.Application.Pensionado.Tipo", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId");
                });
#pragma warning restore 612, 618
        }
    }
}
