// <auto-generated />
using Galvarino.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Galvarino.Web.data.Migrations.pensionado
{
    [DbContext(typeof(PensionadoDbContext))]
    [Migration("20230417150822_homologacion_oficinas")]
    partial class homologacion_oficinas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pensionado")
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Galvarino.Web.Models.Application.Pensionado.HomologacionOficinas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codificacion")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("IdSucursalActividad")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("HomologacionOficinas");
                });
#pragma warning restore 612, 618
        }
    }
}
